{
 "title": "NexentaEdge Cluster",
 "description": "NexentaEdge Cluster overview.",
 "tags": [
  "cluster",
  "nexentaedge"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "SUMMARY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "content": "<center>\n<img src=\"https://nexentaedge.io/img/logo-nexenta-edge.png\" alt=\"NexentaEdge logo\" style=\"height: 80px;\">\n</center>"
  },
  {
   "title": "Status",
   "type": "singlestat",
   "description": "Overall cluster status: HEALTY or DEGRADED",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "nedge_node_degraded" }
   ]
  },
  {
   "title": "Estimated Available",
   "type": "singlestat",
   "description": "Calculated Total cluster available space based on current Redaction Ratio",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "nedge_cluster_estimated_available_bytes"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "singlestat",
   "description": "Total Raw cluster capacity",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "nedge_cluster_capacity_bytes" }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "singlestat",
   "description": "Total Raw used cluster capacity",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "nedge_cluster_physical_used_bytes"
    }
   ]
  },
  {
   "title": "Data Redaction Ratio",
   "type": "singlestat",
   "description": "Calculated current data redaction ratio",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "nedge_cluster_reduction_ratio" }
   ]
  },
  {
   "title": "MD Offload Utilization",
   "type": "singlestat",
   "description": "In case of SSD offload (hybrid deployment) it displays its current average utilization across all the nodes in the cluster",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nedge_node_vdev_mdoffload_size)/sum(nedge_node_vdev_mdoffload_total)"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "singlestat",
   "description": "Total cluster current utilization",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "nedge_cluster_utilization_pct" }
   ]
  },
  {
   "title": "Objects in the Cluster",
   "type": "graph",
   "description": "Total number of all objects in the cluster including S3 parts",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nedge_cluster_objects", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Versions in the Cluster",
   "type": "graph",
   "description": "Total number of all the object versions in the cluster",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nedge_cluster_object_versions", "legendFormat": "Total" }
   ]
  },
  { "title": "TENANTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Client I/O 4K Normalized Latency",
   "type": "graph",
   "description": "Average client I/O 4K normalized latency across all the gateways in the cluster, including mixed and dedicated. For example, 32K transfer would be counted as latency of 8 by 4K blocks.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(nedge_tenant_write4k_latency)",
     "legendFormat": "Write"
    },
    {
     "expr": "avg(nedge_tenant_read4k_latency)",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Client IOPS",
   "type": "graph",
   "description": "Aggregated total and average client I/O IOPS across all the gateways in the cluster, including mixed and dedicated.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(nedge_tenant_writes) by (gid))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(avg(nedge_tenant_reads) by (gid))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Client Throughput",
   "type": "graph",
   "description": "Aggregated total and average client I/O throughput across all the gateways in the cluster, including mixed and dedicated.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg(nedge_tenant_writes_bytes) by(gid))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(avg(nedge_tenant_reads_bytes) by(gid))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Top Tenants",
   "type": "table",
   "description": "Aggregation of activity across top 100 tenants",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(avg(nedge_tenant_writes_bytes+nedge_tenant_reads_bytes) by (tenant,gid)) by (tenant)",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Top Buckets (Read/Write)",
   "type": "table",
   "description": "Aggregation of activity across top 100 buckets",
   "gridPos": { "h": 5, "w": 8, "x": 5, "y": 20 },
   "targets": [
    {
     "expr": "sum(avg(nedge_tenant_writes_bytes+nedge_tenant_reads_bytes) by (bucket,gid)) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Top Objects (Read/Write)",
   "type": "table",
   "description": "Aggregation of activity across top 100 objects",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 20 },
   "targets": [
    {
     "expr": "avg(nedge_tenant_writes_bytes+nedge_tenant_reads_bytes) by (gid, object)",
     "legendFormat": "{{object}}"
    }
   ]
  },
  { "title": "SERVICES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Top Services",
   "type": "table",
   "description": "Aggregation of activity across top 100 services",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(avg(nedge_tenant_writes_bytes+nedge_tenant_reads_bytes) by (gid,svcname,svctype,tenant)) by (svcname,svctype,tenant)",
     "legendFormat": "{{svcname}}, {{tenant}} ({{svctype}})"
    }
   ]
  },
  {
   "title": "Top S3 Throughput",
   "type": "singlestat",
   "description": "Aggregated S3 throughput across all the gateways in the cluster, including mixed and dedicated.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 26 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(nedge_tenant_writes_bytes{svctype=\"s3\"}+nedge_tenant_reads_bytes{svctype=\"s3\"}) by (gid))"
    }
   ]
  },
  {
   "title": "Top NFS Throughput",
   "type": "singlestat",
   "description": "Aggregated NFS throughput across all the gateways in the cluster, including mixed and dedicated.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 26 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(nedge_tenant_writes_bytes{svctype=\"nfs\"}+nedge_tenant_reads_bytes{svctype=\"nfs\"}) by (gid))"
    }
   ]
  },
  {
   "title": "Top iSCSI Throughput",
   "type": "singlestat",
   "description": "Aggregated iSCSI throughput across all the gateways in the cluster, including mixed and dedicated.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 26 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(nedge_tenant_writes_bytes{svctype=\"iscsi\"}+nedge_tenant_reads_bytes{svctype=\"iscsi\"}) by (gid))"
    }
   ]
  },
  {
   "title": "Top SWIFT Throughput",
   "type": "singlestat",
   "description": "Aggregated SWIFT throughput across all the gateways in the cluster, including mixed and dedicated.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 26 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(nedge_tenant_writes_bytes{svctype=\"swift\"}+nedge_tenant_reads_bytes{svctype=\"swift\"}) by (gid))"
    }
   ]
  },
  {
   "title": "Top NBD Throughput",
   "type": "singlestat",
   "description": "Aggregated NBD throughput across all the gateways in the cluster, including mixed and dedicated.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 26 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(nedge_tenant_writes_bytes{svctype=\"nbd\"}+nedge_tenant_reads_bytes{svctype=\"nbd\"}) by (gid))"
    }
   ]
  },
  {
   "title": "Top Custom Throughput",
   "type": "singlestat",
   "description": "Aggregated internal I/O, or custom libccow throughput across all the gateways in the cluster, including mixed and dedicated.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 26 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(nedge_tenant_writes_bytes{svctype=\"undef\"}+nedge_tenant_reads_bytes{svctype=\"undef\"}) by (gid))"
    }
   ]
  },
  {
   "title": "NFS Services Status",
   "type": "graph",
   "description": "Reported states:\n \n   1    - service fully available\n   0    - service partially available (likely networking issue)\n  -1    - service unavailable (df command isn't working)\n  -2    - service unavailable (showmount command isn't working)\n  -3    - service unavailable (not mounted)",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none", "label": "S T A T E S" }
   ],
   "targets": [
    { "expr": "nedge_nfs_service_status", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "iSCSI Services Status",
   "type": "graph",
   "description": "Reported states:\n \n   1\t- service fully available\n   0\t- service LUNs not found\n  -1\t- service not discoverable (likely networking issue)",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "none", "label": "S T A T E S" }
   ],
   "targets": [
    { "expr": "nedge_iscsi_service_status", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "S3 Services Status",
   "type": "graph",
   "description": "Reported states:\n \n   1\t- service fully available\n   0\t- service bucket HEAD failed\n  -1\t- service object HEAD failed\n  -2\t- service not discoverable (likely networking issue)",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "none", "label": "S T A T E S" }
   ],
   "targets": [
    { "expr": "nedge_s3_service_status", "legendFormat": "{{service}}" }
   ]
  },
  { "title": "NODES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "ONLINE",
   "type": "singlestat",
   "description": "VDEVS currently in online and available state",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "nedge_node_online" }
   ]
  },
  {
   "title": "DEGRADED",
   "type": "singlestat",
   "description": "VDEVS currently in Degraded state",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "nedge_node_degraded" }
   ]
  },
  {
   "title": "Memory Utilization (excl. caches)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "nedge_node_memused/nedge_node_memtotal",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Avg. CPU Load 1min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nedge_node_cpuload1", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Swap Used",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "nedge_node_swapused", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Time Deviation",
   "type": "singlestat",
   "description": "Maximum difference between the cluster nodes time",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 35 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(nedge_node_local_timestamp_us)-min(nedge_node_local_timestamp_us)"
    }
   ]
  },
  { "title": "VDEVS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "ONLINE",
   "type": "singlestat",
   "description": "VDEVS currently in online and available state",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 40 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "nedge_node_vdevs_online" }
   ]
  },
  {
   "title": "DEGRADED",
   "type": "singlestat",
   "description": "VDEVS currently in Degraded state",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 40 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "nedge_node_vdevs_degraded" }
   ]
  },
  {
   "title": "Total IOPS",
   "type": "singlestat",
   "description": "Total IOPS  across all VDEVs in the cluster",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 40 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(nedge_node_vdev_reads+nedge_node_vdev_writes)"
    }
   ]
  },
  {
   "title": "Avg. Read Latency",
   "type": "singlestat",
   "description": "Average read latency across all VDEVs in the cluster, 4K normalized",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 40 },
   "format": "µs",
   "valueName": "avg",
   "targets": [
    {
     "expr": "quantile(0.75, nedge_node_vdev_read4k_latency)"
    }
   ]
  },
  {
   "title": "Avg. Read Latency",
   "type": "singlestat",
   "description": "Average read latency across all VDEVs in the cluster, 4K normalized",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 40 },
   "format": "µs",
   "valueName": "avg",
   "targets": [
    {
     "expr": "quantile(0.75, nedge_node_vdev_write4k_latency)"
    }
   ]
  },
  {
   "title": "Total Read Throughput",
   "type": "singlestat",
   "description": "Total read throughput across all VDEVs in the cluster",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 40 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(nedge_node_vdev_reads_bytes)"
    }
   ]
  },
  {
   "title": "Total Write Throughput",
   "type": "singlestat",
   "description": "Total write throughput across all VDEVs in the cluster",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 40 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(nedge_node_vdev_writes_bytes)"
    }
   ]
  },
  {
   "title": "IOSTAT Disk Utilization Avg",
   "type": "graph",
   "description": "Bandwidth utilization for all the VDEVs per averaged per node",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(nedge_node_vdev_iostat_busy) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "IOSTAT Disk IOPS Avg",
   "type": "graph",
   "description": "Average VDEVs IOPS per node",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 43 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "avg(nedge_node_vdev_iostat_r_ios+nedge_node_vdev_iostat_w_ios) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "IOSTAT Disk Size Avg",
   "type": "graph",
   "description": "90th quantile of VDEVs IO size per node",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.9,nedge_node_vdev_iostat_size_kb) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "S.M.A.R.T Errors",
   "type": "graph",
   "description": "Aggregation of important error counters per VDEV",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "nedge_node_vdev_smart_total_err",
     "legendFormat": "{{devname}}"
    }
   ]
  },
  {
   "title": "S.M.A.R.T Current Temperature",
   "type": "graph",
   "description": "Reports Current Temperature of all VDEVs in the cluster",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "nedge_node_vdev_smart_temperature_current",
     "legendFormat": "{{devname}}"
    }
   ]
  },
  {
   "title": "S.M.A.R.T. Status",
   "type": "singlestat",
   "description": "Checks Health Status for all the VDEVs in the cluster. Reports FAIL if at least one has a problem.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(nedge_node_vdev_smart_health_status)"
    }
   ]
  },
  {
   "title": "Attention VDEV",
   "type": "singlestat",
   "description": "Checks Health Status for all the VDEVs in the cluster. Reports FAIL if at least one has a problem.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 45 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nedge_node_vdev_smart_health_status == 0"
    }
   ]
  },
  { "title": "BG ACTIVITY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "BG GC",
   "type": "singlestat",
   "description": "Garbage Collectors approximate progress across cluster",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 48 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(nedge_node_vdev_bg_gc_pct)/10"
    }
   ]
  },
  {
   "title": "BG Space Reclaim",
   "type": "singlestat",
   "description": "Space Reclaim approximate progress across cluster",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 48 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(nedge_node_vdev_bg_space_reclaim_pct)/10  "
    }
   ]
  },
  {
   "title": "Transaction Log",
   "type": "singlestat",
   "description": "Transaction Log time behind current",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 48 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "nedge_trlog_behind_secs" }
   ]
  },
  {
   "title": "Temporary Metadata Entries",
   "type": "graph",
   "description": "Temporary metadata entries used for background processes (Deduplication, Deletion, Replication)",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nedge_node_vdev_temporary_md_entries)",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Verification Queue Entries",
   "type": "graph",
   "description": "Temporary metadata used by Deduplication background engine",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nedge_cluster_ver_queue_entries",
     "legendFormat": "Verification Queue Entries"
    }
   ]
  },
  {
   "title": "Replication Queue Entries",
   "type": "graph",
   "description": "Temporary metadata used by Replication background engine",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nedge_cluster_rep_queue_entries",
     "legendFormat": "Replication Queue Entries"
    }
   ]
  }
 ]
}