{
 "title": "NexentaEdge - Cluster",
 "description": "NexentaEdge Cluster overview.",
 "tags": [
  "cluster",
  "nexentaedge"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "SUMMARY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "content": "<center>\n<img src=\"https://nexentaedge.io/img/logo-nexenta-edge.png\" alt=\"NexentaEdge logo\" style=\"height: 80px;\">\n</center>"
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "nedge_node_degraded" }
   ]
  },
  {
   "title": "Estimated Available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "nedge_cluster_estimated_available_bytes"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "nedge_cluster_capacity_bytes" }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "nedge_cluster_physical_used_bytes"
    }
   ]
  },
  {
   "title": "Data Redaction Ratio",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "nedge_cluster_reduction_ratio" }
   ]
  },
  {
   "title": "Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "nedge_cluster_utilization_pct" }
   ]
  },
  {
   "title": "Objects in the Cluster",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nedge_cluster_objects", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Versions in the Cluster",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nedge_cluster_object_versions", "legendFormat": "Total" }
   ]
  },
  { "title": "TENANTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Client I/O 4K Normalized Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(nedge_tenant_write4k_latency)",
     "legendFormat": "Write"
    },
    {
     "expr": "avg(nedge_tenant_read4k_latency)",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Client IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(nedge_tenant_writes) by (gid))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(avg(nedge_tenant_reads) by (gid))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Client Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg(nedge_tenant_writes_bytes) by(gid))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(avg(nedge_tenant_reads_bytes) by(gid))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Top Tenants",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(avg(nedge_tenant_writes_bytes+nedge_tenant_reads_bytes) by (tenant,gid)) by (tenant)",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Top Buckets (Read/Write)",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 5, "y": 20 },
   "targets": [
    {
     "expr": "sum(avg(nedge_tenant_writes_bytes+nedge_tenant_reads_bytes) by (bucket,gid)) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Top Objects (Read/Write)",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 20 },
   "targets": [
    {
     "expr": "avg(nedge_tenant_writes_bytes+nedge_tenant_reads_bytes) by (gid, object)",
     "legendFormat": "{{object}}"
    }
   ]
  },
  { "title": "SERVICES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Top Services",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(avg(nedge_tenant_writes_bytes+nedge_tenant_reads_bytes) by (gid,svcname,svctype,tenant)) by (svcname,svctype,tenant)",
     "legendFormat": "{{svcname}}, {{tenant}} ({{svctype}})"
    }
   ]
  },
  {
   "title": "Top S3 Throughput",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 26 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(nedge_tenant_writes_bytes{svctype=\"s3\"}+nedge_tenant_reads_bytes{svctype=\"s3\"}) by (gid))"
    }
   ]
  },
  {
   "title": "Top NFS Throughput",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 26 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(nedge_tenant_writes_bytes{svctype=\"nfs\"}+nedge_tenant_reads_bytes{svctype=\"nfs\"}) by (gid))"
    }
   ]
  },
  {
   "title": "Top iSCSI Throughput",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 26 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(nedge_tenant_writes_bytes{svctype=\"iscsi\"}+nedge_tenant_reads_bytes{svctype=\"iscsi\"}) by (gid))"
    }
   ]
  },
  {
   "title": "Top SWIFT Throughput",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 26 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(nedge_tenant_writes_bytes{svctype=\"swift\"}+nedge_tenant_reads_bytes{svctype=\"swift\"}) by (gid))"
    }
   ]
  },
  {
   "title": "Top NBD Throughput",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 26 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(nedge_tenant_writes_bytes{svctype=\"nbd\"}+nedge_tenant_reads_bytes{svctype=\"nbd\"}) by (gid))"
    }
   ]
  },
  {
   "title": "Top Custom Throughput",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 26 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(nedge_tenant_writes_bytes{svctype=\"undef\"}+nedge_tenant_reads_bytes{svctype=\"undef\"}) by (gid))"
    }
   ]
  },
  { "title": "NODES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "ONLINE",
   "type": "singlestat",
   "description": "VDEVS currently in online and available state",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "nedge_node_online" }
   ]
  },
  {
   "title": "DEGRADED",
   "type": "singlestat",
   "description": "VDEVS currently in Degraded state",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "nedge_node_degraded" }
   ]
  },
  {
   "title": "Memory Utilization (excl. caches)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 4, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "nedge_node_memused/nedge_node_memtotal",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Avg. CPU Load 1min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nedge_node_cpuload1", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Swap Used",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "nedge_node_swapused", "legendFormat": "{{hostname}}" }
   ]
  },
  { "title": "VDEVS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "ONLINE",
   "type": "singlestat",
   "description": "VDEVS currently in online and available state",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "nedge_node_vdevs_online" }
   ]
  },
  {
   "title": "DEGRADED",
   "type": "singlestat",
   "description": "VDEVS currently in Degraded state",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "nedge_node_vdevs_degraded" }
   ]
  },
  {
   "title": "Total IOPS",
   "type": "singlestat",
   "description": "Total IOPS  across all VDEVs in the cluster",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 36 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(nedge_node_vdev_reads+nedge_node_vdev_writes)"
    }
   ]
  },
  {
   "title": "Avg. Read Latency",
   "type": "singlestat",
   "description": "Average read latency across all VDEVs in the cluster, 4K normalized",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 36 },
   "format": "µs",
   "valueName": "avg",
   "targets": [
    {
     "expr": "quantile(0.75, nedge_node_vdev_read4k_latency)"
    }
   ]
  },
  {
   "title": "Avg. Write Latency",
   "type": "singlestat",
   "description": "Average write latency across all VDEVs in the cluster, 4K normalized",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 36 },
   "format": "µs",
   "valueName": "avg",
   "targets": [
    {
     "expr": "quantile(0.75, nedge_node_vdev_write4k_latency)"
    }
   ]
  },
  {
   "title": "Total Read Throughput",
   "type": "singlestat",
   "description": "Total read throughput across all VDEVs in the cluster",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 36 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(nedge_node_vdev_reads_bytes)"
    }
   ]
  },
  {
   "title": "Total Write Throughput",
   "type": "singlestat",
   "description": "Total write throughput across all VDEVs in the cluster",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 36 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(nedge_node_vdev_writes_bytes)"
    }
   ]
  },
  { "title": "BG ACTIVITY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "BG GC",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 40 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(nedge_node_vdev_bg_gc_pct)/10"
    }
   ]
  },
  {
   "title": "BG Space Reclaim",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 40 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(nedge_node_vdev_bg_space_reclaim_pct)/10  "
    }
   ]
  },
  {
   "title": "Transaction Log",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 40 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "nedge_trlog_behind_secs" }
   ]
  },
  {
   "title": "Temporary Metadata Entries",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nedge_node_vdev_temporary_md_entries)",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Verification Queue Entries",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nedge_cluster_ver_queue_entries",
     "legendFormat": "Verification Queue Entries"
    }
   ]
  },
  {
   "title": "Replication Queue Entries",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nedge_cluster_rep_queue_entries",
     "legendFormat": "Replication Queue Entries"
    }
   ]
  }
 ]
}